"""Touch region extraction, storage, and hit-testing (issue #49).

A touch-capable device reports a stroke (start point, end point,
duration) against the frame it is currently showing. The server resolves
that stroke to an action by hit-testing the coordinates against the
*touch region map* that was extracted when the frame was rendered.

Regions are declared in markup, not drawn in a separate UI. Any node in
the composed page (a grid cell container, a widget's own markup, a
canvas element, or DOM generated by a code element's script) can carry:

* ``data-on-tap="<action spec>"``, the ``button_actions`` string grammar
  (``refresh``, ``page:<id>``, ``rotate_next``, ``webhook:<url>``, …).
* ``data-on-swipe='{"up": "<spec>", "down": "<spec>", …}'``, a JSON
  object mapping swipe directions to action specs.
* ``data-on-slide='{"axis": "y", "action": …}'``, reserved for absolute
  slider gestures. Extracted and stored today, not yet dispatched.

At render time (same Playwright page session as the screenshot, after
the compose/image/font settle waits) ``EXTRACT_REGIONS_JS`` walks the
DOM, shadow roots included, and returns one record per annotated node
with its layout box in frame pixels. The composed page is rendered at
the exact panel size, so no coordinate mapping is needed: boxes are in
the same pixel space the firmware reports strokes in (the frame as
served, before any device-side rotation/mirror).

The map is persisted as ``<composition_digest>.regions.json`` beside the
composition PNG in ``data/core/renders/``, and rewritten on every render
so a page edit that doesn't change pixels (same digest) still refreshes
the actions. A stroke is only ever dispatched against the frame the
finger actually touched: the firmware echoes the frame's artifact digest
and stale strokes are dropped (the device just repaints and the user
taps again on current content).

Overlap resolution mirrors browser event targeting: the deepest
annotated node containing the point wins, document order breaking ties.

mypy --strict applies to this module.
"""

from __future__ import annotations

import json
import logging
import math
from pathlib import Path
from typing import Any, Final

log = logging.getLogger(__name__)

# A stroke whose start->end displacement stays inside this radius is a
# tap; anything longer is a swipe along its dominant axis. Sized for
# fingertip jitter on large panels (the smallest touch target the grid
# editor produces is a whole cell, hundreds of px).
TAP_RADIUS_PX: Final[int] = 30

# Sidecar schema version, bumped if the record shape ever changes.
_SIDECAR_VERSION: Final[int] = 1

GESTURES: Final[tuple[str, ...]] = (
    "tap",
    "swipe_up",
    "swipe_down",
    "swipe_left",
    "swipe_right",
)

# Walks the composed document (piercing shadow roots, in document order)
# and returns the layout box + raw attribute strings for every node that
# declares a touch attribute. Runs in the render's page session after
# the compose/image/font waits, so boxes reflect the final layout of the
# exact frame being screenshotted. Invisible and zero-area nodes are
# skipped: a hidden element must not swallow taps.
EXTRACT_REGIONS_JS: Final[str] = """() => {
    const out = [];
    let order = 0;
    function visible(el, rect) {
        if (rect.width <= 0 || rect.height <= 0) return false;
        const cs = getComputedStyle(el);
        return cs.display !== 'none' && cs.visibility !== 'hidden';
    }
    function walk(root, depth) {
        for (const el of root.children || []) {
            const tap = el.getAttribute && el.getAttribute('data-on-tap');
            const swipe = el.getAttribute && el.getAttribute('data-on-swipe');
            const slide = el.getAttribute && el.getAttribute('data-on-slide');
            if (tap || swipe || slide) {
                const rect = el.getBoundingClientRect();
                if (visible(el, rect)) {
                    out.push({
                        x: Math.round(rect.x),
                        y: Math.round(rect.y),
                        w: Math.round(rect.width),
                        h: Math.round(rect.height),
                        depth: depth,
                        order: order++,
                        tap: tap || null,
                        swipe: swipe || null,
                        slide: slide || null,
                    });
                }
            }
            if (el.shadowRoot) walk(el.shadowRoot, depth + 1);
            walk(el, depth + 1);
        }
    }
    walk(document.documentElement, 0);
    return out;
}"""


def normalize_regions(raw: Any) -> list[dict[str, Any]]:
    """Validate + coerce the browser extraction result into sidecar
    records. Malformed entries are dropped (logged at debug), the JSON
    attributes (``swipe`` / ``slide``) are parsed here so dispatch never
    parses user markup on the hot path."""
    if not isinstance(raw, list):
        return []
    out: list[dict[str, Any]] = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        try:
            x, y = int(entry["x"]), int(entry["y"])
            w, h = int(entry["w"]), int(entry["h"])
            depth = int(entry.get("depth", 0))
            order = int(entry.get("order", 0))
        except (KeyError, TypeError, ValueError):
            log.debug("touch region dropped (bad box): %r", entry)
            continue
        if w <= 0 or h <= 0:
            continue
        tap = entry.get("tap")
        tap = tap.strip() if isinstance(tap, str) and tap.strip() else None
        swipe = _parse_swipe_attr(entry.get("swipe"))
        slide = _parse_json_attr(entry.get("slide"))
        if tap is None and swipe is None and slide is None:
            continue
        out.append(
            {
                "x": x,
                "y": y,
                "w": w,
                "h": h,
                "depth": depth,
                "order": order,
                "tap": tap,
                "swipe": swipe,
                "slide": slide,
            }
        )
    return out


def _parse_json_attr(value: Any) -> dict[str, Any] | None:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        log.debug("touch attribute is not valid JSON: %r", value)
        return None
    return parsed if isinstance(parsed, dict) else None


def _parse_swipe_attr(value: Any) -> dict[str, str] | None:
    """``data-on-swipe`` is a JSON object of direction -> action spec.
    Unknown directions and non-string specs are dropped."""
    parsed = _parse_json_attr(value)
    if parsed is None:
        return None
    out = {
        k: v.strip()
        for k, v in parsed.items()
        if k in ("up", "down", "left", "right") and isinstance(v, str) and v.strip()
    }
    return out or None


# -- sidecar persistence -------------------------------------------------


def regions_sidecar_path(renders_dir: Path, comp_digest: str) -> Path:
    return renders_dir / f"{comp_digest}.regions.json"


def save_regions(renders_dir: Path, comp_digest: str, regions: list[dict[str, Any]]) -> None:
    """Write (or rewrite) the region map for a composition digest.

    Always overwrites: the digest is content-addressed on *pixels*, and
    two renders with identical pixels can differ in touch annotations
    (e.g. the user removed a cell's action), so the latest render's map
    must win. Best-effort: a failed write only costs interactivity on
    that frame, never the push."""
    try:
        path = regions_sidecar_path(renders_dir, comp_digest)
        path.write_text(
            json.dumps({"v": _SIDECAR_VERSION, "regions": regions}),
            encoding="utf-8",
        )
    except OSError:
        log.exception("touch regions: failed to write sidecar for %s", comp_digest)


def load_regions(renders_dir: Path, comp_digest: str) -> list[dict[str, Any]]:
    """Read the region map for a composition digest. Missing or
    malformed sidecar reads as "no regions" (a valid state: most
    dashboards have no touch annotations)."""
    path = regions_sidecar_path(renders_dir, comp_digest)
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if not isinstance(parsed, dict):
        return []
    regions = parsed.get("regions")
    return regions if isinstance(regions, list) else []


# -- stroke classification + hit-testing ---------------------------------


def classify_stroke(x0: int, y0: int, x1: int, y1: int) -> tuple[str, int]:
    """Classify a stroke into ``(gesture, magnitude_px)``.

    ``tap`` when the displacement stays within ``TAP_RADIUS_PX``,
    otherwise a swipe along the dominant axis. Magnitude is the absolute
    displacement along that axis (0 for taps), kept for the future
    slide/value path and for the event log."""
    dx, dy = x1 - x0, y1 - y0
    if math.hypot(dx, dy) <= TAP_RADIUS_PX:
        return "tap", 0
    if abs(dx) >= abs(dy):
        return ("swipe_right" if dx > 0 else "swipe_left"), abs(dx)
    return ("swipe_down" if dy > 0 else "swipe_up"), abs(dy)


def hit_test(regions: list[dict[str, Any]], x: int, y: int) -> dict[str, Any] | None:
    """Deepest region containing the point, document order as tiebreak
    (mirrors browser event targeting, so a code element's inner button
    wins over its container, and a canvas hotspot painted above a code
    element wins over the markup below it)."""
    best: dict[str, Any] | None = None
    best_key = (-1, -1)
    for region in regions:
        try:
            rx, ry = int(region["x"]), int(region["y"])
            rw, rh = int(region["w"]), int(region["h"])
        except (KeyError, TypeError, ValueError):
            continue
        if not (rx <= x < rx + rw and ry <= y < ry + rh):
            continue
        key = (int(region.get("depth", 0)), int(region.get("order", 0)))
        if key > best_key:
            best, best_key = region, key
    return best


def resolve_gesture_action(region: dict[str, Any], gesture: str) -> str | None:
    """The action spec a gesture resolves to within a region, or None.

    Only the flat string grammar dispatches today. The object form
    (attribute values starting with ``{``) is reserved for structured
    actions (Home Assistant service calls) and is skipped, not errored,
    so markup written against a future server degrades to a no-op
    rather than a failure. ``slide`` declarations are likewise inert
    until the value-substitution path lands."""
    spec: Any = None
    if gesture == "tap":
        spec = region.get("tap")
    elif gesture.startswith("swipe_"):
        swipe = region.get("swipe")
        if isinstance(swipe, dict):
            spec = swipe.get(gesture.removeprefix("swipe_"))
    if not isinstance(spec, str):
        return None
    text: str = spec.strip()
    if not text or text.startswith("{"):
        return None
    return text
