"""Touch region extraction, storage, and hit-testing (issue #49).

A touch-capable device reports a stroke (start point, end point,
duration) against the frame it is currently showing. The server resolves
that stroke to an action by hit-testing the coordinates against the
*touch region map* that was extracted when the frame was rendered.

Regions are declared in markup, not drawn in a separate UI. Any node in
the composed page (a grid cell container, a widget's own markup, a
canvas element, or DOM generated by a code element's script) can carry:

* ``data-on-tap="<action spec>"``, the ``button_actions`` string grammar
  (``refresh``, ``page:<id>``, ``rotate_next``, ``webhook:<url>``, …).
* ``data-on-swipe='{"up": "<spec>", "down": "<spec>", …}'``, a JSON
  object mapping swipe directions to action specs.
* ``data-on-slide='{"axis": "y", "action": …}'``, reserved for absolute
  slider gestures. Extracted and stored today, not yet dispatched.

At render time (same Playwright page session as the screenshot, after
the compose/image/font settle waits) ``EXTRACT_REGIONS_JS`` walks the
DOM, shadow roots included, and returns one record per annotated node
with its layout box in frame pixels. The composed page is rendered at
the exact panel size, so no coordinate mapping is needed: boxes are in
the same pixel space the firmware reports strokes in (the frame as
served, before any device-side rotation/mirror).

The map is persisted as ``<composition_digest>.regions.json`` beside the
composition PNG in ``data/core/renders/``, and rewritten on every render
so a page edit that doesn't change pixels (same digest) still refreshes
the actions. A stroke is only ever dispatched against the frame the
finger actually touched: the firmware echoes the frame's artifact digest
and stale strokes are dropped (the device just repaints and the user
taps again on current content).

Overlap resolution mirrors browser event targeting: the deepest
annotated node containing the point wins, document order breaking ties.

mypy --strict applies to this module.
"""

from __future__ import annotations

import json
import logging
import math
from pathlib import Path
from typing import Any, Final

log = logging.getLogger(__name__)

# A stroke whose start->end displacement stays inside this radius is a
# tap; anything longer is a swipe along its dominant axis. Sized for
# fingertip jitter on large panels (the smallest touch target the grid
# editor produces is a whole cell, hundreds of px).
TAP_RADIUS_PX: Final[int] = 30

# Sidecar schema version, bumped if the record shape ever changes.
# v2 added ``origin`` + ``dangling`` (phase 2: provenance gate + @name refs).
_SIDECAR_VERSION: Final[int] = 2

# Actions with real-world side effects. Dispatched from a touch region
# only when the region's action came from validated config (an editor /
# MCP-set field or a code element's named actions map), never from raw
# markup, so a third-party widget can't aim a webhook at an arbitrary
# URL just by annotating its own HTML. Navigation-class actions
# (refresh / rotate / step / page) are safe from any origin.
SIDE_EFFECTING_ACTIONS: Final[frozenset[str]] = frozenset({"webhook", "ha"})


def is_side_effecting(spec: str | dict[str, Any]) -> bool:
    """Whether an action spec names a side-effecting action. String form:
    the action name is everything before the first ``:``. Structured
    (dict) form: the ``action`` key."""
    if isinstance(spec, dict):
        return str(spec.get("action") or "").strip() in SIDE_EFFECTING_ACTIONS
    return spec.split(":", 1)[0].strip() in SIDE_EFFECTING_ACTIONS


GESTURES: Final[tuple[str, ...]] = (
    "tap",
    "swipe_up",
    "swipe_down",
    "swipe_left",
    "swipe_right",
)

# Walks the composed document (piercing shadow roots, in document order)
# and returns the layout box + attribute values for every node that
# declares a touch attribute. Runs in the render's page session after
# the compose/image/font waits, so boxes reflect the final layout of the
# exact frame being screenshotted. Invisible and zero-area nodes are
# skipped: a hidden element must not swallow taps.
#
# Two pieces of context ride the walk:
#
# * ``origin``: nodes under a ``data-touch-origin="config"`` marker (the
#   compose template stamps it on containers whose actions come from
#   validated config fields, not raw markup) report ``origin: "config"``.
#   The dispatch gate only honours side-effecting actions from config
#   origin.
# * ``actions``: the nearest ancestor's ``data-touch-actions`` JSON map
#   (a code element's named actions). A whole-attribute ``@name`` value
#   resolves through it, counts as config origin, and an unresolvable
#   name is reported in ``dangling`` instead of dispatching.
EXTRACT_REGIONS_JS: Final[str] = """async () => {
    // Code elements render in sandboxed iframes and mirror their
    // annotated boxes into the parent DOM asynchronously (see
    // decorate.js); wait for every sandbox to report before walking.
    const t0 = Date.now();
    while ((window.__tesseraeTouchPending || 0) > 0 && Date.now() - t0 < 3500) {
        await new Promise((r) => setTimeout(r, 50));
    }
    const out = [];
    let order = 0;
    function visible(el, rect) {
        if (rect.width <= 0 || rect.height <= 0) return false;
        const cs = getComputedStyle(el);
        return cs.display !== 'none' && cs.visibility !== 'hidden';
    }
    function resolveRef(value, actions, region) {
        if (!value) return null;
        if (value[0] !== '@') return { value: value, config: false };
        const name = value.slice(1);
        if (actions && Object.prototype.hasOwnProperty.call(actions, name)) {
            const spec = actions[name];
            return {
                value: typeof spec === 'string' ? spec : JSON.stringify(spec),
                config: true,
            };
        }
        region.dangling.push(name);
        return null;
    }
    function walk(root, depth, origin, actions) {
        for (const el of root.children || []) {
            if (!el.getAttribute) continue;
            let elOrigin = origin;
            const originAttr = el.getAttribute('data-touch-origin');
            if (originAttr === 'config') elOrigin = 'config';
            else if (originAttr === 'markup') elOrigin = 'markup';
            let elActions = actions;
            const rawMap = el.getAttribute('data-touch-actions');
            if (rawMap) {
                try { elActions = JSON.parse(rawMap); } catch (e) { /* keep inherited */ }
            }
            const tap = el.getAttribute('data-on-tap');
            const swipe = el.getAttribute('data-on-swipe');
            const slide = el.getAttribute('data-on-slide');
            if (tap || swipe || slide) {
                const rect = el.getBoundingClientRect();
                if (visible(el, rect)) {
                    const region = {
                        x: Math.round(rect.x),
                        y: Math.round(rect.y),
                        w: Math.round(rect.width),
                        h: Math.round(rect.height),
                        depth: depth,
                        order: order++,
                        tap: null,
                        swipe: null,
                        slide: null,
                        origin: elOrigin,
                        dangling: [],
                    };
                    const t = resolveRef(tap, elActions, region);
                    const s = resolveRef(swipe, elActions, region);
                    const l = resolveRef(slide, elActions, region);
                    if (t) { region.tap = t.value; if (t.config) region.origin = 'config'; }
                    if (s) { region.swipe = s.value; if (s.config) region.origin = 'config'; }
                    if (l) { region.slide = l.value; if (l.config) region.origin = 'config'; }
                    if (region.tap || region.swipe || region.slide || region.dangling.length) {
                        out.push(region);
                    }
                }
            }
            if (el.shadowRoot) walk(el.shadowRoot, depth + 1, elOrigin, elActions);
            walk(el, depth + 1, elOrigin, elActions);
        }
    }
    walk(document.documentElement, 0, 'markup', null);
    return out;
}"""


def normalize_regions(raw: Any) -> list[dict[str, Any]]:
    """Validate + coerce the browser extraction result into sidecar
    records. Malformed entries are dropped (logged at debug), the JSON
    attributes (``swipe`` / ``slide``) are parsed here so dispatch never
    parses user markup on the hot path."""
    if not isinstance(raw, list):
        return []
    out: list[dict[str, Any]] = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        try:
            x, y = int(entry["x"]), int(entry["y"])
            w, h = int(entry["w"]), int(entry["h"])
            depth = int(entry.get("depth", 0))
            order = int(entry.get("order", 0))
        except (KeyError, TypeError, ValueError):
            log.debug("touch region dropped (bad box): %r", entry)
            continue
        if w <= 0 or h <= 0:
            continue
        tap = entry.get("tap")
        tap = tap.strip() if isinstance(tap, str) and tap.strip() else None
        swipe = _parse_swipe_attr(entry.get("swipe"))
        slide = _parse_json_attr(entry.get("slide"))
        raw_dangling = entry.get("dangling")
        dangling = (
            [str(n) for n in raw_dangling if isinstance(n, str)]
            if isinstance(raw_dangling, list)
            else []
        )
        if tap is None and swipe is None and slide is None and not dangling:
            continue
        out.append(
            {
                "x": x,
                "y": y,
                "w": w,
                "h": h,
                "depth": depth,
                "order": order,
                "tap": tap,
                "swipe": swipe,
                "slide": slide,
                "origin": "config" if entry.get("origin") == "config" else "markup",
                "dangling": dangling,
            }
        )
    return out


def _parse_json_attr(value: Any) -> dict[str, Any] | None:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        log.debug("touch attribute is not valid JSON: %r", value)
        return None
    return parsed if isinstance(parsed, dict) else None


def _parse_swipe_attr(value: Any) -> dict[str, str] | None:
    """``data-on-swipe`` is a JSON object of direction -> action spec.
    Unknown directions and non-string specs are dropped."""
    parsed = _parse_json_attr(value)
    if parsed is None:
        return None
    out = {
        k: v.strip()
        for k, v in parsed.items()
        if k in ("up", "down", "left", "right") and isinstance(v, str) and v.strip()
    }
    return out or None


# -- sidecar persistence -------------------------------------------------


def regions_sidecar_path(renders_dir: Path, comp_digest: str) -> Path:
    return renders_dir / f"{comp_digest}.regions.json"


def save_regions(renders_dir: Path, comp_digest: str, regions: list[dict[str, Any]]) -> None:
    """Write (or rewrite) the region map for a composition digest.

    Always overwrites: the digest is content-addressed on *pixels*, and
    two renders with identical pixels can differ in touch annotations
    (e.g. the user removed a cell's action), so the latest render's map
    must win. Best-effort: a failed write only costs interactivity on
    that frame, never the push."""
    try:
        path = regions_sidecar_path(renders_dir, comp_digest)
        path.write_text(
            json.dumps({"v": _SIDECAR_VERSION, "regions": regions}),
            encoding="utf-8",
        )
    except OSError:
        log.exception("touch regions: failed to write sidecar for %s", comp_digest)


def load_regions(renders_dir: Path, comp_digest: str) -> list[dict[str, Any]]:
    """Read the region map for a composition digest. Missing or
    malformed sidecar reads as "no regions" (a valid state: most
    dashboards have no touch annotations)."""
    path = regions_sidecar_path(renders_dir, comp_digest)
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if not isinstance(parsed, dict):
        return []
    regions = parsed.get("regions")
    return regions if isinstance(regions, list) else []


# -- stroke classification + hit-testing ---------------------------------


def classify_stroke(x0: int, y0: int, x1: int, y1: int) -> tuple[str, int]:
    """Classify a stroke into ``(gesture, magnitude_px)``.

    ``tap`` when the displacement stays within ``TAP_RADIUS_PX``,
    otherwise a swipe along the dominant axis. Magnitude is the absolute
    displacement along that axis (0 for taps), kept for the future
    slide/value path and for the event log."""
    dx, dy = x1 - x0, y1 - y0
    if math.hypot(dx, dy) <= TAP_RADIUS_PX:
        return "tap", 0
    if abs(dx) >= abs(dy):
        return ("swipe_right" if dx > 0 else "swipe_left"), abs(dx)
    return ("swipe_down" if dy > 0 else "swipe_up"), abs(dy)


def hit_test(regions: list[dict[str, Any]], x: int, y: int) -> dict[str, Any] | None:
    """Latest-in-document-order region containing the point (depth as
    tiebreak). Document order mirrors paint order: descendants come
    after their containers (so a code element's inner button wins over
    its wrapper), and a later sibling (a hotspot painted above a code
    element) wins over everything below it."""
    best: dict[str, Any] | None = None
    best_key = (-1, -1)
    for region in regions:
        try:
            rx, ry = int(region["x"]), int(region["y"])
            rw, rh = int(region["w"]), int(region["h"])
        except (KeyError, TypeError, ValueError):
            continue
        if not (rx <= x < rx + rw and ry <= y < ry + rh):
            continue
        key = (int(region.get("order", 0)), int(region.get("depth", 0)))
        if key > best_key:
            best, best_key = region, key
    return best


def resolve_gesture_action(region: dict[str, Any], gesture: str) -> str | dict[str, Any] | None:
    """The action spec a gesture resolves to within a region, or None.

    Returns either the flat string grammar (``page:<id>`` /
    ``webhook:<url>`` / …) or a structured dict action (currently
    ``{"action": "ha", "domain": …, "service": …, "data": {…}}``).
    Attribute values that look like JSON objects parse into the dict
    form; a malformed or unrecognised structured value reads as None (a
    no-op, never an error, so markup written against a newer server
    degrades cleanly)."""
    spec: Any = None
    if gesture == "tap":
        spec = region.get("tap")
    elif gesture.startswith("swipe_"):
        swipe = region.get("swipe")
        if isinstance(swipe, dict):
            spec = swipe.get(gesture.removeprefix("swipe_"))
    return coerce_action(spec)


def coerce_action(spec: Any) -> str | dict[str, Any] | None:
    """Normalise a raw action value into a dispatchable form: a trimmed
    grammar string, a structured dict (parsed from JSON text when
    needed, validated to carry a string ``action`` name), or None."""
    if isinstance(spec, dict):
        return spec if isinstance(spec.get("action"), str) else None
    if not isinstance(spec, str):
        return None
    text: str = spec.strip()
    if not text:
        return None
    if text.startswith("{"):
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if isinstance(parsed, dict) and isinstance(parsed.get("action"), str):
            return parsed
        return None
    return text


# -- slide gestures ------------------------------------------------------


def slide_declaration(region: dict[str, Any]) -> dict[str, Any] | None:
    """The region's slide declaration ``{"axis": "x"|"y", "action": …}``
    when present and usable, else None. ``axis`` defaults to the box's
    longer dimension when omitted."""
    slide = region.get("slide")
    if not isinstance(slide, dict):
        return None
    action = coerce_action(slide.get("action"))
    if action is None:
        return None
    axis = slide.get("axis")
    if axis not in ("x", "y"):
        try:
            axis = "x" if int(region.get("w", 0)) >= int(region.get("h", 0)) else "y"
        except (TypeError, ValueError):
            axis = "x"
    return {"axis": axis, "action": action}


def slide_value(region: dict[str, Any], axis: str, x: int, y: int) -> int:
    """The 0-100 value a point maps to along a slider region's axis.

    Horizontal: left edge = 0, right edge = 100. Vertical: BOTTOM edge =
    0, top edge = 100 (a brightness bar fills upward). The point is
    clamped to the region so a stroke that drifts past an edge pins to
    the end stop."""
    rx, ry = int(region["x"]), int(region["y"])
    rw, rh = max(1, int(region["w"])), max(1, int(region["h"]))
    frac = 1.0 - (min(max(y - ry, 0), rh) / rh) if axis == "y" else min(max(x - rx, 0), rw) / rw
    return round(frac * 100)


def substitute_value(action: str | dict[str, Any], value: int) -> str | dict[str, Any]:
    """Replace ``{value}`` placeholders in an action with the slide value.

    String specs get a plain text substitution (``webhook:…?v={value}``).
    Structured dicts are deep-copied with every string leaf substituted;
    a leaf that is exactly ``"{value}"`` becomes the integer itself so HA
    service fields like ``brightness_pct`` receive a number, not text."""

    def _sub(node: Any) -> Any:
        if isinstance(node, str):
            if node == "{value}":
                return value
            return node.replace("{value}", str(value))
        if isinstance(node, dict):
            return {k: _sub(v) for k, v in node.items()}
        if isinstance(node, list):
            return [_sub(v) for v in node]
        return node

    result: str | dict[str, Any] = _sub(action)
    return result
