"""Touch region extraction, storage, and hit-testing (issue #49).

A touch-capable device reports a stroke (start point, end point,
duration) against the frame it is currently showing. The server resolves
that stroke to an action by hit-testing the coordinates against the
*touch region map* that was extracted when the frame was rendered.

Regions are declared in markup, not drawn in a separate UI. Any node in
the composed page (a grid cell container, a widget's own markup, a
canvas element, or DOM generated by a code element's script) can carry:

* ``data-on-tap="<action spec>"``, the ``button_actions`` string grammar
  (``refresh``, ``page:<id>``, ``rotate_next``, ``webhook:<url>``, …).
* ``data-on-swipe='{"up": "<spec>", "down": "<spec>", …}'``, a JSON
  object mapping swipe directions to action specs.
* ``data-on-slide='{"axis": "y", "action": …}'``, reserved for absolute
  slider gestures. Extracted and stored today, not yet dispatched.

At render time (same Playwright page session as the screenshot, after
the compose/image/font settle waits) ``EXTRACT_REGIONS_JS`` walks the
DOM, shadow roots included, and returns one record per annotated node
with its layout box in frame pixels. The composed page is rendered at
the exact panel size, so no coordinate mapping is needed: boxes are in
the same pixel space the firmware reports strokes in (the frame as
served, before any device-side rotation/mirror).

The map is persisted as ``<composition_digest>.regions.json`` beside the
composition PNG in ``data/core/renders/``, and rewritten on every render
so a page edit that doesn't change pixels (same digest) still refreshes
the actions. A stroke is only ever dispatched against the frame the
finger actually touched: the firmware echoes the frame's artifact digest
and stale strokes are dropped (the device just repaints and the user
taps again on current content).

Overlap resolution mirrors browser event targeting: the deepest
annotated node containing the point wins, document order breaking ties.

mypy --strict applies to this module.
"""

from __future__ import annotations

import json
import logging
import math
from pathlib import Path
from typing import Any, Final

log = logging.getLogger(__name__)

# A stroke whose start->end displacement stays inside this radius is a
# tap; anything longer is a swipe along its dominant axis. Sized for
# fingertip jitter on large panels (the smallest touch target the grid
# editor produces is a whole cell, hundreds of px).
TAP_RADIUS_PX: Final[int] = 30

# Sidecar schema version, bumped if the record shape ever changes.
# v2 added ``origin`` + ``dangling`` (phase 2: provenance gate + @name refs).
# v3 added the optional ``slots`` list (overlay value slots, hybrid render
# mode); readers of ``regions`` are unaffected.
_SIDECAR_VERSION: Final[int] = 3

# Actions with real-world side effects. Dispatched from a touch region
# only when the region's action came from validated config (an editor /
# MCP-set field or a code element's named actions map), never from raw
# markup, so a third-party widget can't aim a webhook at an arbitrary
# URL just by annotating its own HTML. Navigation-class actions
# (refresh / rotate / step / page) are safe from any origin.
SIDE_EFFECTING_ACTIONS: Final[frozenset[str]] = frozenset({"webhook", "webhook_refresh", "ha"})


def is_side_effecting(spec: str | dict[str, Any]) -> bool:
    """Whether an action spec names a side-effecting action. String form:
    the action name is everything before the first ``:``. Structured
    (dict) form: the ``action`` key."""
    if isinstance(spec, dict):
        return str(spec.get("action") or "").strip() in SIDE_EFFECTING_ACTIONS
    return spec.split(":", 1)[0].strip() in SIDE_EFFECTING_ACTIONS


GESTURES: Final[tuple[str, ...]] = (
    "tap",
    "swipe_up",
    "swipe_down",
    "swipe_left",
    "swipe_right",
)

# Walks the composed document (piercing shadow roots, in document order)
# and returns the layout box + attribute values for every node that
# declares a touch attribute. Runs in the render's page session after
# the compose/image/font waits, so boxes reflect the final layout of the
# exact frame being screenshotted. Invisible and zero-area nodes are
# skipped: a hidden element must not swallow taps.
#
# Two pieces of context ride the walk:
#
# * ``origin``: nodes under a ``data-touch-origin="config"`` marker (the
#   compose template stamps it on containers whose actions come from
#   validated config fields, not raw markup) report ``origin: "config"``.
#   The dispatch gate only honours side-effecting actions from config
#   origin.
# * ``actions``: the nearest ancestor's ``data-touch-actions`` JSON map
#   (a code element's named actions). A whole-attribute ``@name`` value
#   resolves through it, counts as config origin, and an unresolvable
#   name is reported in ``dangling`` instead of dispatching.
EXTRACT_REGIONS_JS: Final[str] = """async () => {
    // Code elements render in sandboxed iframes and mirror their
    // annotated boxes into the parent DOM asynchronously (see
    // decorate.js); wait for every sandbox to report before walking.
    const t0 = Date.now();
    while ((window.__tesseraeTouchPending || 0) > 0 && Date.now() - t0 < 3500) {
        await new Promise((r) => setTimeout(r, 50));
    }
    const out = [];
    let order = 0;
    function visible(el, rect) {
        if (rect.width <= 0 || rect.height <= 0) return false;
        const cs = getComputedStyle(el);
        return cs.display !== 'none' && cs.visibility !== 'hidden';
    }
    function resolveRef(value, actions, region) {
        if (!value) return null;
        if (value[0] !== '@') return { value: value, config: false };
        const name = value.slice(1);
        if (actions && Object.prototype.hasOwnProperty.call(actions, name)) {
            const spec = actions[name];
            return {
                value: typeof spec === 'string' ? spec : JSON.stringify(spec),
                config: true,
            };
        }
        region.dangling.push(name);
        return null;
    }
    function walk(root, depth, origin, actions) {
        for (const el of root.children || []) {
            if (!el.getAttribute) continue;
            let elOrigin = origin;
            const originAttr = el.getAttribute('data-touch-origin');
            if (originAttr === 'config') elOrigin = 'config';
            else if (originAttr === 'markup') elOrigin = 'markup';
            let elActions = actions;
            const rawMap = el.getAttribute('data-touch-actions');
            if (rawMap) {
                try { elActions = JSON.parse(rawMap); } catch (e) { /* keep inherited */ }
            }
            const tap = el.getAttribute('data-on-tap');
            const swipe = el.getAttribute('data-on-swipe');
            const slide = el.getAttribute('data-on-slide');
            if (tap || swipe || slide) {
                const rect = el.getBoundingClientRect();
                if (visible(el, rect)) {
                    const region = {
                        x: Math.round(rect.x),
                        y: Math.round(rect.y),
                        w: Math.round(rect.width),
                        h: Math.round(rect.height),
                        depth: depth,
                        order: order++,
                        tap: null,
                        swipe: null,
                        slide: null,
                        origin: elOrigin,
                        dangling: [],
                        tid: el.getAttribute('data-touch-id')
                            || el.getAttribute('data-el-id') || null,
                    };
                    const t = resolveRef(tap, elActions, region);
                    const s = resolveRef(swipe, elActions, region);
                    const l = resolveRef(slide, elActions, region);
                    if (t) { region.tap = t.value; if (t.config) region.origin = 'config'; }
                    if (s) { region.swipe = s.value; if (s.config) region.origin = 'config'; }
                    if (l) { region.slide = l.value; if (l.config) region.origin = 'config'; }
                    if (region.tap || region.swipe || region.slide || region.dangling.length) {
                        out.push(region);
                    }
                }
            }
            if (el.shadowRoot) walk(el.shadowRoot, depth + 1, elOrigin, elActions);
            walk(el, depth + 1, elOrigin, elActions);
        }
    }
    walk(document.documentElement, 0, 'markup', null);
    return out;
}"""


def normalize_regions(raw: Any) -> list[dict[str, Any]]:
    """Validate + coerce the browser extraction result into sidecar
    records. Malformed entries are dropped (logged at debug), the JSON
    attributes (``swipe`` / ``slide``) are parsed here so dispatch never
    parses user markup on the hot path."""
    if not isinstance(raw, list):
        return []
    out: list[dict[str, Any]] = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        try:
            x, y = int(entry["x"]), int(entry["y"])
            w, h = int(entry["w"]), int(entry["h"])
            depth = int(entry.get("depth", 0))
            order = int(entry.get("order", 0))
        except (KeyError, TypeError, ValueError):
            log.debug("touch region dropped (bad box): %r", entry)
            continue
        if w <= 0 or h <= 0:
            continue
        tap = entry.get("tap")
        tap = tap.strip() if isinstance(tap, str) and tap.strip() else None
        raw_swipe = entry.get("swipe")
        swipe = _parse_swipe_attr(raw_swipe)
        swipe_unusable = swipe is None and _swipe_attr_present_but_unusable(raw_swipe)
        slide = _parse_json_attr(entry.get("slide"))
        raw_dangling = entry.get("dangling")
        dangling = (
            [str(n) for n in raw_dangling if isinstance(n, str)]
            if isinstance(raw_dangling, list)
            else []
        )
        if tap is None and swipe is None and slide is None and not dangling and not swipe_unusable:
            continue
        # Flag any declared action that wouldn't actually dispatch, so
        # render_report / the editor overlay don't green-light a region
        # whose payload is stored but undispatchable (issue #49).
        invalid: list[dict[str, Any]] = []
        if tap is not None:
            reason = action_invalid_reason(tap)
            if reason:
                invalid.append({"gesture": "tap", "reason": reason})
        if isinstance(swipe, dict):
            for direction, sspec in swipe.items():
                reason = action_invalid_reason(sspec)
                if reason:
                    invalid.append({"gesture": f"swipe_{direction}", "reason": reason})
        if swipe_unusable:
            invalid.append(
                {
                    "gesture": "swipe",
                    "reason": (
                        "swipe needs a per-direction map, e.g. "
                        '{"left":"rotate_next"} or '
                        '{"left":{"action":"ha","domain":"light","service":"toggle"}}; '
                        "a bare action object with no up/down/left/right key won't fire"
                    ),
                }
            )
        if isinstance(slide, dict) and slide.get("action") is not None:
            reason = action_invalid_reason(slide.get("action"))
            if reason:
                invalid.append({"gesture": "slide", "reason": reason})
        record = {
            "x": x,
            "y": y,
            "w": w,
            "h": h,
            "depth": depth,
            "order": order,
            "tap": tap,
            "swipe": swipe,
            "slide": slide,
            "origin": "config" if entry.get("origin") == "config" else "markup",
            "dangling": dangling,
            "invalid": invalid,
        }
        # Stable-id hint for the protocol-v2 interaction manifest: an
        # explicit data-touch-id (author-pinned) or the canvas element id
        # the compose template stamps as data-el-id. Optional; regions
        # without one get a content-hash id at manifest build time.
        tid = entry.get("tid")
        if isinstance(tid, str) and tid.strip():
            record["touch_id"] = tid.strip()[:64]
        out.append(record)
    return out


def _parse_json_attr(value: Any) -> dict[str, Any] | None:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        log.debug("touch attribute is not valid JSON: %r", value)
        return None
    return parsed if isinstance(parsed, dict) else None


_SWIPE_DIRECTIONS = ("up", "down", "left", "right")


def _parse_swipe_attr(value: Any) -> dict[str, Any] | None:
    """``data-on-swipe`` is a JSON object mapping a direction (up / down /
    left / right) to an action spec: either a grammar string
    (``"rotate_next"``) or a structured HA object (``{"action":"ha",…}``),
    the same forms ``on_tap`` accepts. Unknown directions are dropped;
    an empty result reads as "no swipe"."""
    parsed = _parse_json_attr(value)
    if parsed is None:
        return None
    out: dict[str, Any] = {}
    for k, v in parsed.items():
        if k not in _SWIPE_DIRECTIONS:
            continue
        if isinstance(v, str) and v.strip():
            out[k] = v.strip()
        elif isinstance(v, dict) and v:
            out[k] = v
    return out or None


def _swipe_attr_present_but_unusable(value: Any) -> bool:
    """True when a swipe attribute was written but resolves to no usable
    direction (e.g. an inline ``{"service":…}`` with no up/down/left/right
    keys). Lets normalize_regions surface a diagnostic instead of silently
    dropping the author's intent (issue #49)."""
    parsed = _parse_json_attr(value)
    return isinstance(parsed, dict) and bool(parsed) and _parse_swipe_attr(value) is None


# -- overlay slot extraction (hybrid render mode, schema 1 slice 2) --------

# Combined extraction: the touch-region walk plus a second pass that
# collects overlay value slots (``data-overlay-key`` nodes). Composed by
# string interpolation so the regions walker stays byte-identical; the
# slots walker pierces shadow roots the same way. Code-element iframes
# are origin-less, so slots inside them arrive the same way their touch
# regions do: the sandbox collector posts them out and the compose page
# mirrors them as annotated marker divs this walker CAN see
# (static/panels/decorate.js).
EXTRACT_INTERACTIVE_JS: Final[str] = (
    """async () => {
    const regions = await ("""
    + EXTRACT_REGIONS_JS
    + """)();
    const slots = [];
    const walk = (root) => {
        for (const el of root.querySelectorAll('[data-overlay-key]')) {
            const rect = el.getBoundingClientRect();
            if (rect.width <= 0 || rect.height <= 0) continue;
            const cs = getComputedStyle(el);
            slots.push({
                x: Math.round(rect.x),
                y: Math.round(rect.y),
                w: Math.round(rect.width),
                h: Math.round(rect.height),
                key: el.getAttribute('data-overlay-key') || '',
                suffix: el.getAttribute('data-overlay-suffix') || '',
                map: el.getAttribute('data-overlay-map') || '',
                align: cs.textAlign,
                px: Math.round(parseFloat(cs.fontSize) || 0),
                weight: parseInt(cs.fontWeight, 10) || 400,
            });
        }
        for (const el of root.querySelectorAll('*')) {
            if (el.shadowRoot) walk(el.shadowRoot);
        }
    };
    walk(document);
    return {regions: regions, slots: slots};
}"""
)


def split_capture_result(raw: Any) -> tuple[Any, Any]:
    """``(raw_regions, raw_slots)`` from a capture script result.

    Tolerates both shapes: the combined ``EXTRACT_INTERACTIVE_JS`` dict
    and the legacy bare regions list (older prewarmed entries, or a
    script failure that degraded to None)."""
    if isinstance(raw, dict):
        return raw.get("regions"), raw.get("slots")
    return raw, None


_SLOT_ALIGNS: Final[frozenset[str]] = frozenset({"left", "center", "right"})


def _parse_slot_map(value: Any) -> dict[str, str] | None:
    """``data-overlay-map``: a small JSON object mapping a raw value to
    its display string (``{"on": "1", "off": "0"}``), so non-numeric
    states can land inside the numeric glyph charset. Capped and
    string-string only; anything else reads as no map."""
    parsed = _parse_json_attr(value)
    if parsed is None:
        return None
    out = {
        str(k)[:47]: str(v)[:47]
        for k, v in list(parsed.items())[:16]
        if isinstance(k, str) and isinstance(v, str)
    }
    return out or None


def normalize_slots(raw: Any) -> list[dict[str, Any]]:
    """Validate + coerce extracted overlay slots into sidecar records.

    Key grammar: ``ha:<entity_id>`` (state) or
    ``ha:<entity_id>:<dotted.path>`` (attribute path, e.g.
    ``ha:light.desk:attributes.brightness``). An optional ``map``
    (from ``data-overlay-map``) rewrites raw values to display strings.
    Weight buckets to 400/700 (the two Inter faces the atlas rasterizer
    ships), align collapses to left/center/right, font size clamps to a
    sane range. Malformed entries are dropped."""
    if not isinstance(raw, list):
        return []
    out: list[dict[str, Any]] = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        try:
            x, y = int(entry["x"]), int(entry["y"])
            w, h = int(entry["w"]), int(entry["h"])
            px = int(entry.get("px") or 0)
        except (KeyError, TypeError, ValueError):
            continue
        key = entry.get("key")
        if not isinstance(key, str) or not key.startswith("ha:") or len(key) <= 3:
            continue
        if w <= 0 or h <= 0 or not (8 <= px <= 200):
            continue
        suffix = entry.get("suffix")
        align = entry.get("align")
        try:
            weight = int(entry.get("weight") or 400)
        except (TypeError, ValueError):
            weight = 400
        record = {
            "x": x,
            "y": y,
            "w": w,
            "h": h,
            "key": key,
            "suffix": suffix[:8] if isinstance(suffix, str) else "",
            "align": align if align in _SLOT_ALIGNS else "left",
            "px": px,
            "weight": 700 if weight >= 600 else 400,
        }
        slot_map = _parse_slot_map(entry.get("map"))
        if slot_map is not None:
            record["map"] = slot_map
        out.append(record)
    return out


# -- sidecar persistence -------------------------------------------------


def regions_sidecar_path(renders_dir: Path, comp_digest: str) -> Path:
    return renders_dir / f"{comp_digest}.regions.json"


def save_regions(
    renders_dir: Path,
    comp_digest: str,
    regions: list[dict[str, Any]],
    *,
    slots: list[dict[str, Any]] | None = None,
) -> None:
    """Write (or rewrite) the region map for a composition digest.

    Always overwrites: the digest is content-addressed on *pixels*, and
    two renders with identical pixels can differ in touch annotations
    (e.g. the user removed a cell's action), so the latest render's map
    must win. ``slots`` (overlay value slots, v3) share the sidecar so
    both maps are measured against the same DOM. Best-effort: a failed
    write only costs interactivity on that frame, never the push."""
    try:
        path = regions_sidecar_path(renders_dir, comp_digest)
        payload: dict[str, Any] = {"v": _SIDECAR_VERSION, "regions": regions}
        if slots:
            payload["slots"] = slots
        path.write_text(json.dumps(payload), encoding="utf-8")
    except OSError:
        log.exception("touch regions: failed to write sidecar for %s", comp_digest)


def load_slots(renders_dir: Path, comp_digest: str) -> list[dict[str, Any]]:
    """Overlay value slots for a composition digest; missing or pre-v3
    sidecars read as "no slots"."""
    path = regions_sidecar_path(renders_dir, comp_digest)
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if not isinstance(parsed, dict):
        return []
    slots = parsed.get("slots")
    return slots if isinstance(slots, list) else []


def load_regions(renders_dir: Path, comp_digest: str) -> list[dict[str, Any]]:
    """Read the region map for a composition digest. Missing or
    malformed sidecar reads as "no regions" (a valid state: most
    dashboards have no touch annotations)."""
    path = regions_sidecar_path(renders_dir, comp_digest)
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if not isinstance(parsed, dict):
        return []
    regions = parsed.get("regions")
    return regions if isinstance(regions, list) else []


# -- stroke classification + hit-testing ---------------------------------


def classify_stroke(x0: int, y0: int, x1: int, y1: int) -> tuple[str, int]:
    """Classify a stroke into ``(gesture, magnitude_px)``.

    ``tap`` when the displacement stays within ``TAP_RADIUS_PX``,
    otherwise a swipe along the dominant axis. Magnitude is the absolute
    displacement along that axis (0 for taps), kept for the future
    slide/value path and for the event log."""
    dx, dy = x1 - x0, y1 - y0
    if math.hypot(dx, dy) <= TAP_RADIUS_PX:
        return "tap", 0
    if abs(dx) >= abs(dy):
        return ("swipe_right" if dx > 0 else "swipe_left"), abs(dx)
    return ("swipe_down" if dy > 0 else "swipe_up"), abs(dy)


def hit_test(regions: list[dict[str, Any]], x: int, y: int) -> dict[str, Any] | None:
    """Latest-in-document-order region containing the point (depth as
    tiebreak). Document order mirrors paint order: descendants come
    after their containers (so a code element's inner button wins over
    its wrapper), and a later sibling (a hotspot painted above a code
    element) wins over everything below it."""
    best: dict[str, Any] | None = None
    best_key = (-1, -1)
    for region in regions:
        try:
            rx, ry = int(region["x"]), int(region["y"])
            rw, rh = int(region["w"]), int(region["h"])
        except (KeyError, TypeError, ValueError):
            continue
        if not (rx <= x < rx + rw and ry <= y < ry + rh):
            continue
        key = (int(region.get("order", 0)), int(region.get("depth", 0)))
        if key > best_key:
            best, best_key = region, key
    return best


def resolve_gesture_action(region: dict[str, Any], gesture: str) -> str | dict[str, Any] | None:
    """The action spec a gesture resolves to within a region, or None.

    Returns either the flat string grammar (``page:<id>`` /
    ``webhook:<url>`` / …) or a structured dict action (currently
    ``{"action": "ha", "domain": …, "service": …, "data": {…}}``).
    Attribute values that look like JSON objects parse into the dict
    form; a malformed or unrecognised structured value reads as None (a
    no-op, never an error, so markup written against a newer server
    degrades cleanly)."""
    spec: Any = None
    if gesture == "tap":
        spec = region.get("tap")
    elif gesture.startswith("swipe_"):
        swipe = region.get("swipe")
        if isinstance(swipe, dict):
            spec = swipe.get(gesture.removeprefix("swipe_"))
    return coerce_action(spec)


def coerce_action(spec: Any) -> str | dict[str, Any] | None:
    """Normalise a raw action value into a dispatchable form: a trimmed
    grammar string, a structured dict, or None.

    Structured actions are normalised generously so the natural Home
    Assistant shapes an agent is likely to write all resolve to the
    canonical ``{"action":"ha","domain","service","data":{...}}`` form:

    * an explicit ``"action":"ha"`` object;
    * an object with no ``action`` but a ``service`` (``action:"ha"`` is
      inferred, since a service call is unambiguous);
    * a dotted ``"service":"light.turn_on"`` splits into domain+service;
    * an ``entity_id`` at the top level, or under ``target.entity_id``
      (the HA-native shape), is folded into ``data``.

    A dict with an unrecognised ``action`` name is returned as-is so
    validation can name it; anything that can't be made into an action
    returns None."""
    if isinstance(spec, dict):
        return _coerce_dict_action(spec)
    if not isinstance(spec, str):
        return None
    text: str = spec.strip()
    if not text:
        return None
    if text.startswith("{"):
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        return _coerce_dict_action(parsed) if isinstance(parsed, dict) else None
    return text


def _coerce_dict_action(d: dict[str, Any]) -> dict[str, Any] | None:
    """Normalise a structured (dict) action. See :func:`coerce_action`."""
    name = d.get("action")
    if isinstance(name, str) and name.strip():
        name = name.strip()
        return _normalize_ha(d) if name == "ha" else {**d, "action": name}
    # No explicit action name: a service call is unambiguously an HA action.
    if d.get("service"):
        return _normalize_ha(d)
    return None


# Top-level keys that carry structure, not service data. Everything else
# an agent puts at the top level (``brightness_pct``, ``color_name``, …) is
# folded into ``data``, so the flat HA shape ``{service, entity_id,
# brightness_pct}`` dispatches the same as the nested ``{service, data:{…}}``.
_HA_RESERVED_KEYS = frozenset({"action", "domain", "service", "target", "data", "entity_id"})


def _normalize_ha(d: dict[str, Any]) -> dict[str, Any]:
    """Canonicalise an HA action into ``{action, domain, service, data}``,
    folding the common shape variations. domain/service may be empty when
    the input is incomplete; :func:`action_invalid_reason` reports that."""
    service = str(d.get("service") or "").strip()
    domain = str(d.get("domain") or "").strip()
    if not domain and "." in service:
        domain, _, service = service.partition(".")
        domain, service = domain.strip(), service.strip()
    raw = d.get("data")
    data: dict[str, Any] = dict(raw) if isinstance(raw, dict) else {}
    if "entity_id" not in data:
        eid = d.get("entity_id")
        if not eid and isinstance(d.get("target"), dict):
            eid = d["target"].get("entity_id")
        if eid:
            data["entity_id"] = eid
    # Hoist any remaining top-level keys as service data: the natural flat
    # HA form puts brightness_pct / color_name / etc. beside entity_id, not
    # under a ``data`` block. Explicit ``data`` keys win over hoisted ones.
    for key, value in d.items():
        if key not in _HA_RESERVED_KEYS and key not in data:
            data[key] = value
    # A comma-joined entity_id is a common hand-written shape; HA wants a
    # list, so split it (entity ids never contain commas).
    eid = data.get("entity_id")
    if isinstance(eid, str) and "," in eid:
        data["entity_id"] = [part.strip() for part in eid.split(",") if part.strip()]
    return {"action": "ha", "domain": domain, "service": service, "data": data}


def canonical_action(spec: Any) -> str | dict[str, Any] | None:
    """Canonicalise a single stored action for persistence (issue #49).

    The models run this on write so a dashboard's on_tap / on_swipe /
    on_slide are stored in the dispatchable form, not the raw shape an
    agent happened to type. That keeps the canvas editor's Interaction
    panel able to decode it (it recognises ``{"action":"ha",…}``, not the
    flat ``{"service":…}`` variant), and means dispatch and the editor see
    the same thing. An empty value normalises to None; a value that isn't
    a recognisable action is kept as-is so validation / render_report can
    still flag it rather than silently dropping the author's intent."""
    if spec is None:
        return None
    if isinstance(spec, str) and not spec.strip():
        return None
    coerced = coerce_action(spec)
    return coerced if coerced is not None else spec


def canonical_swipe(value: Any) -> dict[str, Any] | None:
    """Canonicalise an ``on_swipe`` direction map's values in place."""
    if not isinstance(value, dict):
        return value if value else None
    out: dict[str, Any] = {}
    for direction, spec in value.items():
        canon = canonical_action(spec)
        if canon is not None:
            out[direction] = canon
    return out or None


def canonical_slide(value: Any) -> dict[str, Any] | None:
    """Canonicalise the ``action`` inside an ``on_slide`` declaration."""
    if not isinstance(value, dict):
        return value if value else None
    if value.get("action") is None:
        return value or None
    return {**value, "action": canonical_action(value["action"])}


# Action names that ``button_actions.dispatch`` knows plus the structured
# actions the touch dispatcher handles. Used to flag regions whose action
# would never fire, so render_report / the editor don't green-light a dead
# dashboard (issue #49).
def action_invalid_reason(spec: Any) -> str | None:
    """Why an action wouldn't dispatch, or None if it's fine.

    Mirrors what dispatch actually accepts: a known string verb
    (``refresh`` / ``rotate_next`` / ``step:<n>`` / ``page:<id>`` /
    ``webhook:<url>``) or a structured HA call with a domain + service.
    Anything else is reported so verification reflects reality rather
    than echoing a stored-but-undispatchable payload."""
    action = coerce_action(spec)
    if action is None:
        return (
            "not a usable action (expected a spec string like 'page:<id>' "
            'or an {"action":"ha","domain":...,"service":...} object)'
        )
    if isinstance(action, dict):
        if action.get("action") != "ha":
            return f"unknown structured action {action.get('action')!r}"
        if not action.get("domain") or not action.get("service"):
            return 'HA action needs a "domain" and a "service"'
        return None
    from app.button_actions import registered_actions

    verb = action.split(":", 1)[0].strip()
    if verb not in registered_actions():
        return f"unknown action {verb!r}"
    return None


# -- slide gestures ------------------------------------------------------


def slide_declaration(region: dict[str, Any]) -> dict[str, Any] | None:
    """The region's slide declaration ``{"axis": "x"|"y", "action": …}``
    when present and usable, else None. ``axis`` defaults to the box's
    longer dimension when omitted."""
    slide = region.get("slide")
    if not isinstance(slide, dict):
        return None
    action = coerce_action(slide.get("action"))
    if action is None:
        return None
    axis = slide.get("axis")
    if axis not in ("x", "y"):
        try:
            axis = "x" if int(region.get("w", 0)) >= int(region.get("h", 0)) else "y"
        except (TypeError, ValueError):
            axis = "x"
    return {"axis": axis, "action": action}


def slide_value(region: dict[str, Any], axis: str, x: int, y: int) -> int:
    """The 0-100 value a point maps to along a slider region's axis.

    Horizontal: left edge = 0, right edge = 100. Vertical: BOTTOM edge =
    0, top edge = 100 (a brightness bar fills upward). The point is
    clamped to the region so a stroke that drifts past an edge pins to
    the end stop."""
    rx, ry = int(region["x"]), int(region["y"])
    rw, rh = max(1, int(region["w"])), max(1, int(region["h"]))
    frac = 1.0 - (min(max(y - ry, 0), rh) / rh) if axis == "y" else min(max(x - rx, 0), rw) / rw
    return round(frac * 100)


def substitute_value(action: str | dict[str, Any], value: int) -> str | dict[str, Any]:
    """Replace ``{value}`` placeholders in an action with the slide value.

    String specs get a plain text substitution (``webhook:…?v={value}``).
    Structured dicts are deep-copied with every string leaf substituted;
    a leaf that is exactly ``"{value}"`` becomes the integer itself so HA
    service fields like ``brightness_pct`` receive a number, not text."""

    def _sub(node: Any) -> Any:
        if isinstance(node, str):
            if node in ("{value}", "$value"):
                return value
            return node.replace("{value}", str(value)).replace("$value", str(value))
        if isinstance(node, dict):
            return {k: _sub(v) for k, v in node.items()}
        if isinstance(node, list):
            return [_sub(v) for v in node]
        return node

    result: str | dict[str, Any] = _sub(action)
    return result
