#!/usr/bin/env python3
"""Generate docs/widgets/gallery.md from the live plugin manifests.

Reads every ``plugins/<id>/plugin.json`` with ``kind == "widget"``, pulls
each widget's stability tier from the README's tier tables, groups the
widgets by family (the ``<family>_<role>`` id prefix), and emits one
Material "grid card" per widget linking its screenshot (captured
separately by ``scripts/capture_widget_shots.py``).

Run from the repo root:  ``python scripts/gen_widget_gallery.py``
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = REPO_ROOT / "plugins"
README = REPO_ROOT / "README.md"
SHOTS_REL = "../screenshots/widgets"  # relative to docs/widgets/gallery.md
SHOTS_DIR = REPO_ROOT / "docs" / "screenshots" / "widgets"
OUT = REPO_ROOT / "docs" / "widgets" / "gallery.md"

# Friendly family names, keyed by the id prefix. Anything unlisted falls
# back to a title-cased prefix.
FAMILIES: dict[str, str] = {
    "weather": "Weather",
    "clock": "Clocks & time",
    "calendar": "Calendar",
    "f1": "Formula 1",
    "github": "GitHub",
    "news": "News & feeds",
    "finance": "Finance",
    "sky": "Sky & astronomy",
    "ha": "Home Assistant",
    "spotify": "Spotify",
    "picture": "Pictures",
    "public": "Transit",
    "todo": "Productivity",
    "webpage": "Web",
}

# Render order for the family sections.
FAMILY_ORDER = [
    "weather",
    "clock",
    "calendar",
    "f1",
    "github",
    "news",
    "finance",
    "sky",
    "ha",
    "spotify",
    "picture",
    "public",
    "todo",
    "webpage",
]


def _load_tiers() -> dict[str, str]:
    """Map widget id -> tier label by parsing the README's
    '## Widget stability tiers' section. Each '### <Tier>' subsection owns
    every backtick-wrapped id that appears before the next heading."""
    if not README.exists():
        return {}
    text = README.read_text(encoding="utf-8")
    start = text.find("## Widget stability tiers")
    if start == -1:
        return {}
    # Stop at the next top-level (## ) heading.
    end = text.find("\n## ", start + 1)
    section = text[start : end if end != -1 else len(text)]

    tiers: dict[str, str] = {}
    current: str | None = None
    for line in section.splitlines():
        m = re.match(r"^###\s+(.*\S)", line)
        if m:
            heading = m.group(1).strip()
            current = heading if heading.lower() != "tier policy" else None
            continue
        if current:
            for wid in re.findall(r"`([a-z][a-z0-9_]*)`", line):
                # First tier wins (a widget shouldn't appear twice, but be safe).
                tiers.setdefault(wid, current)
    return tiers


def _widgets() -> list[dict]:
    out: list[dict] = []
    for child in sorted(PLUGINS_DIR.iterdir()):
        manifest = child / "plugin.json"
        if not child.is_dir() or not manifest.exists():
            continue
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        if data.get("kind") != "widget":
            continue
        data["_id"] = child.name
        out.append(data)
    return out


def _tier_for(wid: str, manifest: dict, tiers: dict[str, str]) -> str:
    if wid in tiers:
        return tiers[wid]
    needs_net = bool(manifest.get("render", {}).get("needs_network"))
    return "Local" if not needs_net else "-"


def _family(wid: str) -> str:
    return wid.split("_", 1)[0]


def _card(manifest: dict, tier: str) -> str:
    wid = manifest["_id"]
    name = manifest.get("name", wid)
    desc = manifest.get("description", "").strip()
    sizes = manifest.get("supports", {}).get("sizes", [])
    size_str = " ".join(f"`{s}`" for s in sizes) if sizes else "-"
    shot = SHOTS_DIR / f"{wid}.png"
    if shot.exists():
        img = f"![{wid}]({SHOTS_REL}/{wid}.png)"
    else:
        img = "_Screenshot pending, run `python scripts/capture_widget_shots.py`._"

    return (
        f"-   **{name}** &middot; `{wid}`\n\n"
        f"    ---\n\n"
        f"    {img}\n\n"
        f"    {desc}\n\n"
        f"    **Sizes:** {size_str} &middot; **Tier:** {tier}\n"
    )


def render() -> str:
    tiers = _load_tiers()
    widgets = _widgets()
    by_family: dict[str, list[dict]] = {}
    for w in widgets:
        by_family.setdefault(_family(w["_id"]), []).append(w)

    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by scripts/gen_widget_gallery.py, do not edit by hand. -->")
    lines.append("")
    lines.append("# Widget gallery")
    lines.append("")
    lines.append(
        f"The **{len(widgets)} widgets** that ship with Tesserae. Each is a "
        "drop-a-folder plugin under `plugins/<id>/`; drop your own in and it "
        "shows up in the editor's picker. Want to build one? See "
        "[Build a widget with AI](../dev/writing-a-plugin.md)."
    )
    lines.append("")
    lines.append(
        '!!! note "Stability tiers"\n'
        "    **Stable** = backed by an official, documented API. "
        "**Best-effort** = undocumented but long-lived endpoint. "
        "**Fragile** = scraping or a soft policy, convenience only. "
        "**Local** = computed on the host, no upstream to break. "
        "See [Screens & compatibility](../compatibility.md) for the hardware side."
    )
    lines.append("")

    ordered = FAMILY_ORDER + sorted(set(by_family) - set(FAMILY_ORDER))
    for fam in ordered:
        members = by_family.get(fam)
        if not members:
            continue
        title = FAMILIES.get(fam, fam.replace("_", " ").title())
        lines.append(f"## {title}")
        lines.append("")
        lines.append('<div class="grid cards" markdown>')
        lines.append("")
        for manifest in sorted(members, key=lambda m: m["_id"]):
            tier = _tier_for(manifest["_id"], manifest, tiers)
            lines.append(_card(manifest, tier))
        lines.append("</div>")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    n = render().count("-   **")
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({n} widget cards)")


if __name__ == "__main__":
    main()
