#!/usr/bin/env python3
"""Generate docs/widgets/community.md from the catalog's widgets.json.

Fetches the catalog index from ``dmellok/tesserae-widgets`` (or the URL
in ``--catalog``), reads every entry, emits one Material "grid card"
per bundle linking the lg screenshot hosted on the catalog repo's raw
URL. Same shape as ``gen_widget_gallery.py`` for the bundled widgets,
so the two pages feel like halves of the same gallery.

Run from the repo root:  ``python scripts/gen_community_gallery.py``

Idempotent; re-run when the catalog gains a new entry or you bump a
release. The wiki build script (mkdocs) re-runs it on every deploy.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "docs" / "widgets" / "community.md"

DEFAULT_CATALOG_URL = "https://raw.githubusercontent.com/dmellok/tesserae-widgets/main/widgets.json"
SCREENSHOTS_BASE = "https://raw.githubusercontent.com/dmellok/tesserae-widgets/main/screenshots"

# Friendly section names per tag. Tags come from the catalog schema's
# closed enum; unknown tags fall through to a "Other" section.
TAG_SECTIONS: dict[str, str] = {
    "weather": "Weather",
    "clock": "Clocks & time",
    "calendar": "Calendar",
    "news": "News & feeds",
    "finance": "Finance",
    "github": "GitHub",
    "media": "Music & media",
    "sports": "Sports",
    "transit": "Transit",
    "home-assistant": "Home Assistant",
    "utility": "Utilities & monitoring",
}

# Curated section order so the page reads top-down by interest.
SECTION_ORDER = [
    "Weather",
    "Clocks & time",
    "Calendar",
    "News & feeds",
    "Finance",
    "GitHub",
    "Music & media",
    "Sports",
    "Transit",
    "Home Assistant",
    "Utilities & monitoring",
    "Other",
]


HEADER = """\
<!-- AUTO-GENERATED by scripts/gen_community_gallery.py, do not edit by hand. -->

# Community widgets gallery

Widgets that don't ship in Tesserae's default install but are one click
away via **Settings → Widgets → Browse community widgets**. The
catalog is curated, every entry is reviewed before it lands.

If your dashboard is missing a widget that used to be in the bundle
(F1, Spotify, GitHub, etc.), it's here.

## How install works

1. Open **Settings → Widgets → Browse community widgets** in Tesserae.
2. Click **Install** on the entry you want. Tesserae downloads the
   release tarball, verifies its sha256 against the catalog, and
   drops the widget folders into `plugins/`.
3. Restart Tesserae (or click **Restart now** in the banner) so the
   plugin loader picks them up.
4. The widget appears in the composition picker on the next page
   edit.

Uninstalling is the same flow in reverse, with the option to keep or
delete the plugin's data dir.

## Trust model

Audit-only review: every catalog entry is a PR to
[dmellok/tesserae-widgets](https://github.com/dmellok/tesserae-widgets)
that the maintainer reads end-to-end before merge. The runtime also
enforces network egress per widget via the [`requires:` capability
declarations](../widgets.md#capabilities-requires); extended-palette
widgets are flagged in the entry. See [Publish via the
catalog](../dev/publishing-a-widget.md) for the reviewer's
checklist.

The catalog is the right home for widgets that:

- Need an account or API key (Spotify, GitHub, Apple Developer).
- Serve a niche audience (F1, OctoPrint, region-specific data).
- Are variants of an already-bundled archetype (a fancier clock,
  another weather variant).

!!! tip "Verified badge"
    Entries marked **verified** are reviewed + maintained by the
    catalog owner; the source repos belong to the catalog
    maintainer. The badge doesn't endorse the third-party service a
    widget connects to (Spotify, GitHub, etc.); it certifies the
    widget code itself.

"""


FOOTER = """\

---

Want to contribute one? See
[Publish via the catalog](../dev/publishing-a-widget.md). The path is
the same whether you're contributing a single widget or a bundle of
related ones.
"""


def _fetch(url: str) -> dict[str, Any]:
    req = urllib.request.Request(url, headers={"User-Agent": "tesserae-docs-build"})
    with urllib.request.urlopen(req, timeout=20) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _section_for(entry: dict[str, Any]) -> str:
    tags = entry.get("tags") or []
    for tag in tags:
        if tag in TAG_SECTIONS:
            return TAG_SECTIONS[tag]
    return "Other"


def _card(entry: dict[str, Any]) -> str:
    eid = entry["id"]
    name = entry["name"]
    desc = entry["description"]
    folders = entry.get("folders") or [eid]
    source = entry.get("source", "")
    version = entry.get("release", {}).get("version", "")
    verified = entry.get("official", False)
    screenshot_url = (
        f"{SCREENSHOTS_BASE}/{eid}/lg.png" if "lg" in entry.get("screenshot_sizes", []) else None
    )

    badge = (
        " <span style='background:var(--md-accent-fg-color);color:white;"
        "padding:0.05em 0.5em;border-radius:999px;font-size:0.7em;"
        "vertical-align:middle;'>verified</span>"
        if verified
        else ""
    )

    if len(folders) > 1:
        folders_note = f"**Bundle:** installs {len(folders)} folders &middot; " + " ".join(
            f"`{f}`" for f in folders
        )
    else:
        folders_note = f"**Folder:** `{folders[0]}`"

    img = f"    ![{eid}]({screenshot_url})" if screenshot_url else "    *(no screenshot yet)*"

    lines = [
        f"-   **{name}**{badge} &middot; `{eid}`",
        "",
        "    ---",
        "",
        img,
        "",
        f"    {desc}",
        "",
        f"    {folders_note} &middot; **Version:** `v{version}`"
        if version
        else f"    {folders_note}",
    ]
    if source:
        lines.append("")
        lines.append(f"    [Source repository]({source})")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--catalog",
        default=DEFAULT_CATALOG_URL,
        help=f"Catalog widgets.json URL (default: {DEFAULT_CATALOG_URL})",
    )
    args = parser.parse_args()

    try:
        catalog = _fetch(args.catalog)
    except Exception as err:
        print(f"could not fetch catalog: {err}", file=sys.stderr)
        return 1

    widgets = sorted(catalog.get("widgets", []), key=lambda w: w["name"].lower())
    by_section: dict[str, list[dict[str, Any]]] = {}
    for w in widgets:
        by_section.setdefault(_section_for(w), []).append(w)

    body_parts: list[str] = [HEADER]
    for section in SECTION_ORDER:
        entries = by_section.pop(section, [])
        if not entries:
            continue
        body_parts.append(f"\n## {section}\n")
        body_parts.append('<div class="grid cards" markdown>\n')
        body_parts.extend(_card(e) + "\n" for e in entries)
        body_parts.append("</div>\n")
    # Any unexpected sections (forward-compat with new tag enum values).
    for section, entries in sorted(by_section.items()):
        body_parts.append(f"\n## {section}\n")
        body_parts.append('<div class="grid cards" markdown>\n')
        body_parts.extend(_card(e) + "\n" for e in entries)
        body_parts.append("</div>\n")

    body_parts.append(FOOTER)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(body_parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({len(widgets)} community entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
